import "server-only";

export const PAGE_WIDTH = 595.28;
export const PAGE_HEIGHT = 841.89;
export const MARGIN = 56;
export const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
export const BOTTOM_LIMIT = PAGE_HEIGHT - MARGIN - 16;
export const FOOTER_TOP = PAGE_HEIGHT - 44;

/** Typography scale: title / section / body / caption. */
export const TYPE = {
  title: 24,
  section: 16,
  body: 11,
  caption: 9,
} as const;

export const COLOR = {
  ink: "#0f172a",
  muted: "#64748b",
  faint: "#94a3b8",
  border: "#e2e8f0",
  surface: "#f8fafc",
  track: "#e9eef4",
  white: "#ffffff",
  primary: "#4f46e5",
  primarySoft: "#eef2ff",
  emerald: "#059669",
  emeraldSoft: "#ecfdf5",
  emeraldText: "#047857",
  sky: "#0284c7",
  skySoft: "#f0f9ff",
  skyText: "#0369a1",
  amber: "#d97706",
  amberSoft: "#fffbeb",
  amberText: "#b45309",
  rose: "#e11d48",
  roseSoft: "#fef2f2",
  roseText: "#be123c",
  neutralSoft: "#f1f5f9",
} as const;

export type Severity = "HIGH" | "MEDIUM" | "LOW";

export const STATUS = [
  {
    min: 95,
    label: "Excellent",
    color: COLOR.emerald,
    soft: COLOR.emeraldSoft,
    text: COLOR.emeraldText,
  },
  {
    min: 80,
    label: "Good",
    color: COLOR.sky,
    soft: COLOR.skySoft,
    text: COLOR.skyText,
  },
  {
    min: 65,
    label: "Average",
    color: COLOR.amber,
    soft: COLOR.amberSoft,
    text: COLOR.amberText,
  },
  {
    min: 0,
    label: "Needs improvement",
    color: COLOR.rose,
    soft: COLOR.roseSoft,
    text: COLOR.roseText,
  },
] as const;

export function getStatus(score: number) {
  return STATUS.find((status) => score >= status.min) ?? STATUS[STATUS.length - 1];
}

export function severityColor(severity: Severity) {
  if (severity === "HIGH") return COLOR.rose;
  if (severity === "MEDIUM") return COLOR.amber;
  return COLOR.muted;
}

export function severitySoft(severity: Severity) {
  if (severity === "HIGH") return COLOR.roseSoft;
  if (severity === "MEDIUM") return COLOR.amberSoft;
  return COLOR.neutralSoft;
}

export function formatDate(iso: string | null): string {
  if (!iso) return "—";
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) return "—";
  return date.toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });
}

export function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value));
}

export function measureText(
  doc: PDFKit.PDFDocument,
  text: string,
  font: string,
  size: number,
): number {
  const prevFont = (doc as PDFDocumentWithArc)._font;
  const prevSize = (doc as PDFDocumentWithArc)._fontSize;
  doc.font(font).fontSize(size);
  const width = doc.widthOfString(text);
  (doc as PDFDocumentWithArc)._font = prevFont;
  (doc as PDFDocumentWithArc)._fontSize = prevSize;
  return width;
}

export function textHeight(
  doc: PDFKit.PDFDocument,
  text: string,
  opts: PDFKit.Mixins.TextOptions,
): number {
  return doc.heightOfString(text, opts);
}

/** Truncate `text` with an ellipsis so it fits `maxWidth` on a single line. */
export function truncateToWidth(
  doc: PDFKit.PDFDocument,
  text: string,
  font: string,
  size: number,
  maxWidth: number,
): string {
  const limit = maxWidth + 0.01;
  if (measureText(doc, text, font, size) <= limit) return text;
  let remaining = text;
  while (remaining.length > 0) {
    const candidate = `${remaining.slice(0, -1)}…`;
    if (measureText(doc, candidate, font, size) <= limit) return candidate;
    remaining = remaining.slice(0, -1);
  }
  return "…";
}

export interface PDFDocumentWithArc extends PDFKit.PDFDocument {
  arc(x: number, y: number, r: number, start: number, end: number, anti?: boolean): this;
  _font: unknown;
  _fontSize: number;
}

/** Adds a page when the current one cannot fit `needed` more points. Returns true on break. */
export function ensureSpace(doc: PDFKit.PDFDocument, needed: number): boolean {
  if (doc.y + needed > BOTTOM_LIMIT) {
    doc.addPage();
    doc.y = MARGIN;
    return true;
  }
  return false;
}

/** Ensures a block of `height` fits as a unit; breaks to a new page if needed. */
export function beginBlock(doc: PDFKit.PDFDocument, height: number): number {
  if (doc.y + height > BOTTOM_LIMIT) {
    doc.addPage();
    doc.y = MARGIN;
  }
  return doc.y;
}

/** Kaiken AI brand mark: filled rounded square with a white "K". */
export function drawBrandMark(doc: PDFKit.PDFDocument, x: number, y: number, size: number) {
  doc.save();
  doc.fillColor(COLOR.primary).roundedRect(x, y, size, size, size * 0.28).fill();
  doc.fillColor(COLOR.white).font("Helvetica-Bold").fontSize(size * 0.6).text("K", x, y + size * 0.2, {
    width: size,
    align: "center",
    lineBreak: false,
  });
  doc.restore();
}

/** Report footer with brand + "Generated by Kaiken AI" and the page number. */
export function drawFooter(doc: PDFKit.PDFDocument, page: number) {
  doc.save();
  const ruleY = FOOTER_TOP - 12;
  doc
    .moveTo(MARGIN, ruleY)
    .lineTo(PAGE_WIDTH - MARGIN, ruleY)
    .lineWidth(0.6)
    .strokeColor(COLOR.border)
    .stroke();
  doc.fillColor(COLOR.primary).rect(MARGIN, FOOTER_TOP - 4, 6, 6).fill();
  doc
    .fillColor(COLOR.muted)
    .font("Helvetica-Bold")
    .fontSize(TYPE.caption)
    .text("Generated by Kaiken AI", MARGIN + 12, FOOTER_TOP - 6.5, { lineBreak: false });
  const pageLabel = `Page ${page}`;
  doc
    .fillColor(COLOR.faint)
    .font("Helvetica")
    .fontSize(TYPE.caption)
    .text(pageLabel, PAGE_WIDTH - MARGIN - measureText(doc, pageLabel, "Helvetica", TYPE.caption), FOOTER_TOP - 6.5, {
      lineBreak: false,
    });
  doc.restore();
}

/** Minimal footer for the resume PDF: centered page number only. */
export function drawResumeFooter(doc: PDFKit.PDFDocument, page: number) {
  doc.save();
  const pageLabel = `Page ${page}`;
  doc
    .fillColor(COLOR.faint)
    .font("Helvetica")
    .fontSize(TYPE.caption)
    .text(pageLabel, PAGE_WIDTH / 2 - measureText(doc, pageLabel, "Helvetica", TYPE.caption) / 2, FOOTER_TOP - 4, {
      lineBreak: false,
    });
  doc.restore();
}

/** Section heading with a small accent bar. */
export function sectionTitle(doc: PDFKit.PDFDocument, text: string) {
  ensureSpace(doc, 64);
  const y = doc.y;
  doc.fillColor(COLOR.primary).rect(MARGIN, y + 3, 3, 15).fill();
  doc
    .font("Helvetica-Bold")
    .fontSize(TYPE.section)
    .fillColor(COLOR.ink)
    .text(text.toUpperCase(), MARGIN + 12, y, { lineGap: 1, characterSpacing: 0.9 });
  doc.y = y + 22;
  doc.moveDown(0.7);
}

/** Resume section heading: uppercase label with a hairline rule underneath. */
export function resumeSectionTitle(doc: PDFKit.PDFDocument, text: string) {
  ensureSpace(doc, 64);
  const y = doc.y;
  doc
    .font("Helvetica-Bold")
    .fontSize(TYPE.section)
    .fillColor(COLOR.primary)
    .text(text.toUpperCase(), MARGIN, y, { characterSpacing: 1.1 });
  doc
    .moveTo(MARGIN, y + 20)
    .lineTo(PAGE_WIDTH - MARGIN, y + 20)
    .lineWidth(0.8)
    .strokeColor(COLOR.border)
    .stroke();
  doc.y = y + 30;
}

/** Rounded pill chip. Returns the drawn width. */
export function drawChip(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  text: string,
  height: number,
  fg: string,
  bg: string,
  fontSize = height - 10,
): number {
  const maxWidth = Math.max(40, PAGE_WIDTH - MARGIN - x - 2);
  const width = Math.min(measureText(doc, text, "Helvetica-Bold", fontSize) + 22, maxWidth);
  const label = truncateToWidth(doc, text, "Helvetica-Bold", fontSize, Math.max(1, width - 22));
  doc.fillColor(bg).roundedRect(x, y, width, height, height / 2).fill();
  doc
    .fillColor(fg)
    .font("Helvetica-Bold")
    .fontSize(fontSize)
    .text(label, x + 11, y + (height - fontSize) / 2);
  return width;
}

/** Status pill with tinted background. Returns the drawn width. */
export function drawStatusPill(
  doc: PDFKit.PDFDocument,
  x: number,
  y: number,
  text: string,
  fg: string,
  bg: string,
  height: number,
  fontSize = 9,
): number {
  const width = measureText(doc, text, "Helvetica-Bold", fontSize) + 26;
  doc.fillColor(bg).roundedRect(x, y, width, height, height / 2).fill();
  doc
    .fillColor(fg)
    .font("Helvetica-Bold")
    .fontSize(fontSize)
    .text(text, x, y + (height - fontSize) / 2, { width, align: "center" });
  return width;
}

export function drawCheckIcon(doc: PDFKit.PDFDocument, x: number, y: number, color: string) {
  doc.save();
  doc
    .strokeColor(color)
    .lineWidth(1.5)
    .lineCap("round")
    .lineJoin("round");
  doc.moveTo(x, y + 3.4).lineTo(x + 3, y + 6.2).lineTo(x + 7.6, y + 0.4).stroke();
  doc.restore();
}

export function drawCrossIcon(doc: PDFKit.PDFDocument, x: number, y: number, color: string) {
  doc.save();
  doc
    .strokeColor(color)
    .lineWidth(1.5)
    .lineCap("round");
  doc.moveTo(x + 1, y + 1).lineTo(x + 7.4, y + 7.4);
  doc.moveTo(x + 7.4, y + 1).lineTo(x + 1, y + 7.4).stroke();
  doc.restore();
}
